# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=200)),
                ('branch', models.TextField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('live_kt', models.IntegerField()),
                ('dead_kt', models.IntegerField()),
                ('profile', models.CharField(max_length=4000)),
                ('passing_year', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
