# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpcprocess', '0002_auto_20160930_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligiCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('tech_skills', models.TextField(max_length=2000)),
                ('min_cgpa', models.TextField(max_length=100)),
                ('live_kt_allowed', models.BooleanField(default=True)),
                ('backlog_allowed', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tpcprocess.Company')),
            ],
        ),
    ]
