# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpcprocess', '0003_eligicriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligicriteria',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='eligicriteria',
            name='min_cgpa',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eligicriteria',
            name='tech_skills',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
