# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpcprocess', '0004_auto_20161002_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tpcprocess.Company')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tpcprocess.Student')),
            ],
        ),
    ]
