# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpcprocess', '0005_candidatelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatelist',
            old_name='is_eligible',
            new_name='is_selected',
        ),
    ]
